/**
 * Public operationId → CLI command (source of truth for coverage CI).
 * Must stay in sync with docs/CLI.md "Full map".
 */
export const SKIPPED_OPERATION_IDS = ['deleteMediaLegacy'] as const;

export const OPERATION_COMMANDS: Record<string, string> = {
  sendMessage: 'message send --text / send --text',
  sendFile: 'message send --file / --media-id',
  createUploadMedia: 'media upload',
  listMessages: 'message list',
  createReadMessage: 'message read',
  sendTemplate: 'template send',
  listTemplates: 'template list',
  addTemplate: 'template add',
  removeTemplate: 'template remove',
  getStatus: 'status / channel status',
  getMe: 'me',
  updateMe: 'me update',
  retrieveMedia: 'media get',
  deleteMedia: 'media delete',
  sendReaction: 'message react',
  sendLocation: 'message location',
  sendLocationRequest: 'message location-request',
  sendContact: 'message contact',
  sendButton: 'message buttons',
  sendList: 'message menu',
  sendCarousel: 'message carousel',
  sendProduct: 'message product',
  sendCtaUrl: 'message cta',
  sendAddressMessage: 'message address',
  sendOrderDetails: 'message order',
  sendPaymentRequest: 'message payment',
  sendSticker: 'message sticker',
  sendFlow: 'message flow',
  getWebhook: 'webhook get',
  setWebhook: 'webhook set',
  listSettings: 'channel settings',
  createSettings: 'channel settings set / webhook clear',
  getMmLiteStatus: 'channel mm-lite',
  getCommerce: 'catalog get',
  createCommerce: 'catalog set',
  getConversationalAutomation: 'channel automation',
  setConversationalAutomation: 'channel automation set',
  blockUser: 'user block',
  unblockUser: 'user unblock',
  listBlockedUsers: 'user blocked',
  createGroups: 'group create',
  listGroups: 'group list',
  getGroupsGroupId: 'group get',
  createGroupsGroupId: 'group update',
  deleteGroupsGroupId: 'group delete',
  getGroupsGroupIdInvitelink: 'group invite-link',
  createGroupsGroupIdInvitelink: 'group invite-link reset',
  createFlows: 'flow create',
  listFlows: 'flow list',
  getFlowsFlowId: 'flow get',
  deleteFlowsFlowId: 'flow delete',
  patchFlowsFlowIdMetadata: 'flow metadata',
  patchFlowsFlowIdAssets: 'flow assets',
  getFlowsFlowIdPreview: 'flow preview',
  createFlowsFlowIdPublish: 'flow publish',
  createFlowsFlowIdDeprecate: 'flow deprecate',
  getCallingSettings: 'call settings',
  updateCallingSettings: 'call settings set',
  initiateCall: 'call connect / pre-accept / accept / reject / hangup',
  getWhatsappBusinessEncryption: 'flow encryption',
  setWhatsappBusinessEncryption: 'flow encryption set',
};

export const COMPLETION_COMMANDS = [
  'init',
  'send',
  'message',
  'template',
  'channel',
  'me',
  'status',
  'media',
  'group',
  'flow',
  'webhook',
  'user',
  'catalog',
  'call',
  'completion',
  'version',
] as const;
